index:
    path: /
    controller: App\Controller\DefaultController::index

insert:
    path: /insert
    controller: App\Controller\DefaultController::insert

config:
    path: /config
    controller: App\Controller\DefaultController::config
